name: Snake Animation

on:
  schedule:
    - cron: "* */12 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Platane/snk@v2
      with:
        github_user_name: daiccordeiro # Substitua pelo seu nome de usuário
        outputs: dist

    - name: Generate snake animation
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: output
        build_dir: dist

    - name: Commit snake animation
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add -A
        git commit -m "Atualizando a animação da cobrinha"
        git push origin output
