name: Cobrinha ReadME

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Correção para executar a cada 12 horas no início de cada hora
  workflow_dispatch: # Permitir execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: daiccordeiro
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Validar se o arquivo foi gerado corretamente
      - name: Validate Snake Animation Output
        run: |
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            echo "Snake animation SVG not generated!"
            exit 1
          fi
          echo "Snake animation SVG generated successfully."

      # Publicar animação no branch `output`
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Log final indicando sucesso
      - name: Workflow Completed
        run: echo "Snake animation updated successfully and deployed to GitHub Pages."

